name: planny
description: "An appllication for the Driving Schools"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.8
  http: ^0.13.5
  curl_logger_dio_interceptor: ^0.0.3
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  provider: ^6.0.5
  injectable: ^2.1.0
  get_it: ^7.2.0
  flutter_svg: ^2.0.2
  dio: ^4.0.4
  equatable: ^2.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shimmer: ^3.0.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator:
  build_runner:
  import_sorter: ^4.6.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  intl_translation: ^0.20.0

flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true

import_sorter:
  ignored_files: # Optional, defaults to []
    - \/l10n\/*
    - \/generated\/*
    - \/injection.config.dart
    - \/firebase_options.dart
    - \/test/mocks/*
